version: '3.7'
services:
  mysql:
    container_name: "mysql-skeleton"
    image: 'mysql:8.0.31'
    working_dir: /data
    volumes:
      - 'mysql_data:/data'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hyperf
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    ports:
      - '39002:3306'
  app-skeleton:
    container_name: sample-sqlcommenter-hyperf-poc
    image: sample-sqlcommenter-hyperf-app
    user: "${UID}:${GID}"
    build:
      context: .docker/development
    tty: true
    volumes:
      - ./:/opt/www
    ports:
      - "9501:8080"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - PHP_IDE_CONFIG=serverName=sample-sqlcommenter-hyperf-poc
      - DB_DATABASE=hyperf
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
      - DB_HOST=mysql
      - TRACER_DRIVER=zipkin
      - ZIPKIN_ENDPOINT_URL=http://collector:9411/api/v2/spans
    depends_on:
      - mysql
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.39.0
    volumes:
      - './.docker/development/collector-config.yaml:/etc/otel/config.yaml'
    depends_on:
      - zipkin
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - '9411:9411'

volumes:
  mysql_data: {}