receivers:
  zipkin:

exporters:
  logging:
    logLevel: debug
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

service:
  pipelines:
    traces:
      receivers:
        - zipkin
      exporters:
        - logging
        - zipkin